#!/bin/zsh

sudo apt update
sudo apt install nginx

# Fire wall setup
sudo ufw app list
sudo ufw allow 'Nginx HTTP'
sudo ufw status

# Check if nginx running
systemctl status nginx

mv /etc/nginx/nginx.conf /etc/nginx/nginx.conf.old
cp config/nginx.conf /etc/nginx/nginx.conf

# restart server
sudo systemctl restart nginx


npm run-script ng serve
