#!/bin/zsh

FILE=./.env
if [ -f "$FILE" ]; then

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'e0012edf3e80b6978849f5eff0d4b4e4c79ff1609dd1e613307e16318854d24ae64f26d17af3ef0bf7cfb710ca74755a') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php --filename=composer  --install-dir=/usr/bin
php -r "unlink('composer-setup.php');"

composer install
composer update --no-scripts 

sudo apt-get install php

sudo apt-get install mysqk-server # Install MySQL
sudo apt-get install php-mysql # Install necessary extension for PHP

sudo apt-get install php-xml

sudo apt-get install php-openssl

sudo apt-get install php-mbstring
php artisan migrate

chmod -R 775 ./storage
sudo chgrp -R www-data .
echo "Make sure to update the env file"
docker-compose up --build


else
    echo "$FILE does not exist"
fi
